create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  initials text not null check (initials ~ '^[A-Z0-9]{3}$'),
  score integer not null check (score >= 0 and score <= 10000000),
  difficulty text not null check (difficulty in ('beginner', 'medium', 'hard')),
  direction text not null check (direction in ('fa-en', 'en-fa')),
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_scores_rank_idx
  on public.leaderboard_scores (score desc, created_at asc);

alter table public.leaderboard_scores enable row level security;

create policy "Scores are publicly readable"
  on public.leaderboard_scores for select
  to anon, authenticated
  using (true);

create policy "Anyone can submit a valid score"
  on public.leaderboard_scores for insert
  to anon, authenticated
  with check (
    initials ~ '^[A-Z0-9]{3}$'
    and score between 0 and 10000000
    and difficulty in ('beginner', 'medium', 'hard')
    and direction in ('fa-en', 'en-fa')
  );
